name: Monitoring Setup
on:
  workflow_dispatch:
jobs:
  monitoring:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Azure CLI
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Configure Kubernetes Context
        run: |
          az aks get-credentials --resource-group ${{ secrets.RESOURCE_NAME }} --name ${{ secrets.CLUSTER_NAME }}

      - name: Install Helm
        run: |
          curl https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3 | bash

      - name: Add Helm Repositories
        run: |
          helm repo add prometheus-community https://prometheus-community.github.io/helm-charts
          helm repo add grafana https://grafana.github.io/helm-charts
          helm repo update

      - name: Create Namespace for Monitoring
        run: |
          kubectl create namespace monitoring || echo "Namespace monitoring already exists"

      - name: Deploy Prometheus
        run: |
          helm upgrade --install prometheus prometheus-community/prometheus --namespace monitoring

      - name: Deploy Grafana
        run: |
          helm upgrade --install grafana grafana/grafana --namespace monitoring --set adminPassword=${{ secrets.GRAFANA }} --set service.type=LoadBalancer

      - name: Verify Pods
        run: |
          kubectl get pods -n monitoring
